FROM ubuntu:18.04
LABEL maintainer="wang-junjian@qq.com"

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    nano \
    && rm -rf /var/lib/apt/lists/*

ADD requirements.txt /drawing/
WORKDIR /drawing/
RUN pip3 install --no-cache-dir -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple

ADD . /drawing/

EXPOSE 8001

ENTRYPOINT ["python3", "main.py"]

